### ISSUE TITLE
crash with gtnh mixins

### ISSUE THREAD

**Issue by kotmatross28729** [makamys/DMod#5]
Log :  [log.txt](https://github.com/makamys/DMod/files/10148349/log.txt)

**Comment by makamys** [comment]
~~This is a known issue GTNHMixins has with mods that embed Mixin. You can work around it by renaming the GTNHMixins jar to come first alphabetically (e.g. `00gtnhmixins-2.1.1.jar`)~~

Nevermind, just noticed you already did that. So it's something else...

Can you post a mod list?

**Comment by kotmatross28729** [comment]
just dmod and gtnh mixins are enough, mixingasm doesn't help

**Comment by makamys** [comment]
I see, I was able to reproduce it just now.
